[package]
name = "graphqlparser_native"
version = "0.1.0"
authors = []
edition = "2024"

[lib]
name = "graphqlparser_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36.2"
graphql-parser = "0.4.1"
