[package]
name = "graphqlparser_native"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "graphqlparser_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
graphql-parser = "0.4.0"
